import Fallback from '@/components/Fallback';
import Header from '@/components/Header';
import SideNav from '@/components/SideNav';
import TaskNav from '@/components/TaskNav';
import type { Metadata } from 'next';
import { Suspense } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    type: 'website',
    locale: 'en_US',
    // ... add more open graph meta tags
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense fallback={Fallback()}>
      <div className="container mx-auto flex flex-col min-h-screen">
        <Header />
        <main className="flex-grow">
          <TaskNav />
          <div className="flex w-full">
            <SideNav />
            <div className="flex-grow p-3">{children}</div>
          </div>
        </main>
      </div>
    </Suspense>
  );
}
